name: CI/CD ITP CARGO - Innovatech Chile

on:
  push:
    branches:
      - deploy

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 122501127840.dkr.ecr.us-east-1.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login a Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y Push Frontend
        run: |
          docker build -t $ECR_REGISTRY/itp-cargo/front-despacho:${{ github.sha }} ./front_despacho
          docker push $ECR_REGISTRY/itp-cargo/front-despacho:${{ github.sha }}

      - name: Build y Push Backend Ventas
        run: |
          docker build -t $ECR_REGISTRY/itp-cargo/back-ventas:${{ github.sha }} ./back-Ventas_SpringBoot/Springboot-API-REST
          docker push $ECR_REGISTRY/itp-cargo/back-ventas:${{ github.sha }}

      - name: Build y Push Backend Despachos
        run: |
          docker build -t $ECR_REGISTRY/itp-cargo/back-despachos:${{ github.sha }} ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          docker push $ECR_REGISTRY/itp-cargo/back-despachos:${{ github.sha }}
          

      - name: Deploy Frontend a ECS
        run: |
          aws ecs update-service \
            --cluster itp-cargo-cluster \
            --service svc-frontend \
            --force-new-deployment

      - name: Deploy Backend Ventas a ECS
        run: |
          aws ecs update-service \
            --cluster itp-cargo-cluster \
            --service itp-cargo-back-ventas-service-e81lrm11 \
            --force-new-deployment

      - name: Deploy Backend Despachos a ECS
        run: |
          aws ecs update-service \
            --cluster itp-cargo-cluster \
            --service svc-back-despachos \
            --force-new-deployment